package com.game.manager.model.enums;

public enum Skill {
    ATHLETICS, ACROBATICS, SLEIGHT_OF_HAND, STEALTH, ARCANA, HISTORY, INVESTIGATION, NATURE, RELIGION,
    ANIMAL_HANDLING, INSIGHT, MEDICINE, PERCEPTION, SURVIVE, DECEPTION, INTIMIDATION, PERFORMANCE, PERSUASION

}
